export const data = [
    {
        id: 1,
        title: "GameDev Challenge",
        description: "Розробіть гру за 48 годин на будь-якому рушії на тему, яка буде оголошена при старті",
        image: "img-1",
        status: "active",
        statusText: "Активний",
        participants: 95,
        daysLeft: 4,
        endDate: null,
        timeLeft: null,
        joined: false,
        category: "Розробка ігор"
    },
    {
        id: 2,
        title: "Blockchain Innovation",
        description: "Розробіть інноваційні блокчейн-рішення для фінансового сектору. Фокус на безпеці, масштабованості та зручності використання. Переможці отримають можливість співпраці з провідними фінтех-компаніями.",
        image: "img-2",
        status: "active",
        statusText: "Активний",
        participants: 112,
        daysLeft: 8,
        endDate: null,
        timeLeft: null,
        joined: false,
        category: "Блокчейн"
    },
    {
        id: 3,
        title: "Web Dev Challenge",
        description: "Розробіть гру за 48 годин на будь-якому рушії на тему, яка буде оголошена при старті",
        image: "img-3",
        status: "upcoming",
        statusText: "Скоро",
        participants: 57,
        daysToStart: 7,
        joined: false,
        category: "Веб-розробка"
    },
    {
        id: 4,
        title: "AI Solutions Hackathon",
        description: "Розробіть інноваційні рішення з використанням штучного інтелекту для вирішення реальних бізнес-проблем. Учасники матимуть доступ до ексклюзивних наборів даних та API партнерів.",
        image: "img-4",
        status: "upcoming",
        statusText: "Скоро",
        participants: 75,
        daysToStart: 15,
        joined: false,
        category: "Штучний інтелект"
    },
    {
        id: 5,
        title: "GameDev Challenge",
        description: "Розробіть гру за 48 годин на будь-якому рушії на тему, яка буде оголошена при старті",
        image: "img-5",
        status: "active",
        statusText: "Активний",
        participants: 95,
        daysLeft: 4,
        endDate: null,
        timeLeft: null,
        joined: false,
        category: "Розробка ігор"
    },
    {
        id: 6,
        title: "Blockchain Innovation",
        description: "Розробіть інноваційні блокчейн-рішення для фінансового сектору. Фокус на безпеці, масштабованості та зручності використання. Переможці отримають можливість співпраці з провідними фінтех-компаніями.",
        image: "img-6",
        status: "active",
        statusText: "Активний",
        participants: 112,
        daysLeft: 8,
        endDate: null,
        timeLeft: null,
        joined: false,
        category: "Блокчейн"
    },
    {
        id: 7,
        title: "Web Dev Challenge",
        description: "Розробіть гру за 48 годин на будь-якому рушії на тему, яка буде оголошена при старті",
        image: "img-3",
        status: "upcoming",
        statusText: "Скоро",
        participants: 57,
        daysToStart: 7,
        joined: false,
        category: "Веб-розробка"
    },
    {
        id: 8,
        title: "AI Solutions Hackathon",
        description: "Розробіть інноваційні рішення з використанням штучного інтелекту для вирішення реальних бізнес-проблем. Учасники матимуть доступ до ексклюзивних наборів даних та API партнерів.",
        image: "img-4",
        status: "upcoming",
        statusText: "Скоро",
        participants: 75,
        daysToStart: 15,
        joined: false,
        category: "Штучний інтелект"
    }
];